import type { Language } from "./appTypes";

export const copy = {
  en: {
    brand: "FitNest",
    tagline: "Strength, mobility, and calm routines for every day.",
    nav: {
      overview: "Overview",
      library: "Library",
      playlists: "Playlists",
      membership: "Plans",
      admin: "Admin",
    },
    heroEyebrow: "Daily movement",
    heroTitle: "Build a home routine that feels focused, warm, and easy to return to.",
    heroText:
      "Explore guided strength, mobility, recovery, and yoga sessions. Save playlists, choose a plan, and unlock the training pace that fits your week.",
    authTitle: "Account",
    login: "Log in",
    register: "Register",
    logout: "Log out",
    refresh: "Refresh data",
    guestTitle: "Join FitNest",
    guestText:
      "Create an account to save playlists, unlock classes through plans, and keep your access in one place.",
    authName: "Name",
    authEmail: "Email",
    authPassword: "Password",
    authSubmitLogin: "Enter FitNest",
    authSubmitRegister: "Create account",
    overviewTitle: "Your training space",
    overviewText: "See your access level, current plan, and the sessions that are ready for you right now.",
    libraryTitle: "Workout library",
    libraryText: "Browse classes by trainer, category, and the access level included in your plan.",
    searchLabel: "Search",
    searchPlaceholder: "Search by title or description",
    trainerFilter: "Trainer",
    categoryFilter: "Category",
    allTrainers: "All trainers",
    allCategories: "All categories",
    noVideos: "No videos found for the current filters.",
    playlistsTitle: "Your playlists",
    playlistsText: "Build simple weekly collections, rename them anytime, and keep favourite sessions together.",
    createPlaylist: "Create playlist",
    playlistName: "Playlist name",
    selectedVideos: "Selected videos for new playlist",
    noPlaylists: "You do not have any playlists yet.",
    membershipTitle: "Plans and checkout",
    membershipText: "Choose a plan, simulate payment, and unlock the classes included in your access level.",
    subscribe: "Confirm payment",
    activeSubscriptions: "Active subscriptions",
    noSubscriptions: "No subscriptions yet.",
    adminTitle: "Studio admin",
    adminText: "Manage categories, trainers, plans, videos, and members from one calm control room.",
    categoryManager: "Category manager",
    trainerManager: "Trainer manager",
    packageManager: "Package manager",
    videoManager: "Video manager",
    userManager: "User manager",
    adminWorkspaceHint: "Choose a resource and manage it from one focused control panel.",
    adminSearchPlaceholder: "Search in the current admin section",
    adminResetPanel: "Reset panel",
    adminNoMatches: "No records match the current search.",
    adminSelfDeleteBlocked: "Use the logout button instead of deleting the current admin account.",
    save: "Save",
    edit: "Edit",
    delete: "Delete",
    cancel: "Cancel",
    duration: "Duration",
    equipment: "Equipment",
    language: "Language",
    description: "Description",
    videoUrl: "Video URL",
    startDate: "Start date",
    price: "Price",
    durationMonths: "Duration months",
    planName: "Plan name",
    trainerBio: "Bio",
    role: "Role",
    accountStatus: "Account status",
    registerDate: "Registered",
    currentUser: "Current user",
    roleAdmin: "Admin",
    roleTrainer: "Trainer",
    roleUser: "User",
    statusActive: "Active",
    statusSuspended: "Blocked",
    assignPlan: "Add subscription",
    currentPlan: "Current plan",
    dashboardGuestCta: "Sign in to open your library, playlists, and paid access inside FitNest.",
    adminOnly: "Admin tools are visible only for the admin account.",
    choosePlaylist: "Active playlist",
    choosePlaylistFirst: "Choose a playlist first.",
    createOrChoosePlaylist: "Create or choose a playlist to manage its videos.",
    addToPlaylist: "Add to active playlist",
    addedToPlaylist: "Added to playlist",
    removeFromPlaylist: "Remove from active playlist",
    renamePlaylist: "Rename playlist",
    videosInPlaylist: "Videos in playlist",
    emptySelection: "No selected videos",
    statsVideos: "Videos",
    statsTrainers: "Trainers",
    statsCategories: "Categories",
    statsPackages: "Packages",
    statsPlaylists: "Playlists",
    statsSubscriptions: "Subscriptions",
    watchNow: "Watch workout",
    unlockThisVideo: "Unlock this workout",
    simulatedCheckoutTitle: "Simulated checkout",
    simulatedCheckoutText: "Use the demo payment form below to unlock the selected plan and show access changes inside the app.",
    paymentEmail: "Payment email",
    paymentCardholder: "Cardholder",
    paymentCardNumber: "Card number",
    selectPlan: "Choose plan",
    selectedPlan: "Selected plan",
    packageIncludes: "Includes",
    accessLabel: "Current access",
    accessNone: "No active plan",
    accessStarter: "Starter access",
    accessPlus: "Plus access",
    accessFull: "Full access",
    availableNow: "Available now",
    accessNeeded: "Requires",
    openMembership: "View plans",
    closeVideo: "Close video",
    noCategory: "No category",
    noTrainer: "No trainer",
    noLanguage: "No language",
    noEquipment: "No equipment",
    profileFocus: "Member focus",
    trainerDashboard: "Trainer dashboard",
    trainerDashboardText: "See your own sessions and the workout content linked to your trainer profile.",
    nextBestPlan: "Recommended next step",
    paymentSuccess: "Payment simulated and access updated.",
    paymentHint: "This payment form is a safe demo used to show package access inside FitNest.",
    paymentIncomplete: "Complete the simulated payment form first.",
    lockedCount: "locked",
    sessionDetailsSoon: "Session details coming soon.",
    loadingApp: "Opening FitNest…",
    signedOut: "You have been signed out.",
    refreshSuccess: "Your FitNest content has been refreshed.",
    loginSuccess: "Welcome back to FitNest.",
    registerSuccess: "Your FitNest account is ready.",
  },
  et: {
    brand: "FitNest",
    tagline: "Jõud, liikuvus ja rahulik treeningurütm igaks päevaks.",
    nav: {
      overview: "Ülevaade",
      library: "Videoteek",
      playlists: "Pleilistid",
      membership: "Paketid",
      admin: "Admin",
    },
    heroEyebrow: "Igapäevane liikumine",
    heroTitle: "Loo kodune treeningurutiin, kuhu on lihtne tagasi tulla.",
    heroText:
      "Avasta juhendatud jõu-, liikuvus-, taastumis- ja joogatunnid. Salvesta pleiliste, vali pakett ja ava just sinu nädalaga sobiv treeningutempo.",
    authTitle: "Konto",
    login: "Logi sisse",
    register: "Registreeri",
    logout: "Logi välja",
    refresh: "Värskenda andmeid",
    guestTitle: "Liitu FitNestiga",
    guestText:
      "Loo konto, et salvestada pleiliste, avada paketiga treeningud ja hoida kogu ligipääs ühes kohas.",
    authName: "Nimi",
    authEmail: "E-post",
    authPassword: "Parool",
    authSubmitLogin: "Sisene FitNesti",
    authSubmitRegister: "Loo konto",
    overviewTitle: "Sinu treeninguruum",
    overviewText: "Vaata oma ligipääsutaset, aktiivset paketti ja treeninguid, mis on sulle praegu avatud.",
    libraryTitle: "Treeningute videoteek",
    libraryText: "Sirvi treeninguid treeneri, kategooria ja sinu paketis sisalduva ligipääsu järgi.",
    searchLabel: "Otsing",
    searchPlaceholder: "Otsi pealkirja või kirjelduse järgi",
    trainerFilter: "Treener",
    categoryFilter: "Kategooria",
    allTrainers: "Kõik treenerid",
    allCategories: "Kõik kategooriad",
    noVideos: "Praeguste filtritega videoid ei leitud.",
    playlistsTitle: "Sinu pleilistid",
    playlistsText: "Koosta lihtsad nädalaplaanid, nimeta need ümber ja hoia lemmiktreeningud koos.",
    createPlaylist: "Loo pleilist",
    playlistName: "Pleilisti nimi",
    selectedVideos: "Valitud videod uue pleilisti jaoks",
    noPlaylists: "Sul ei ole veel ühtegi pleilisti.",
    membershipTitle: "Paketid ja makse",
    membershipText: "Vali pakett, tee demomakse ja ava selle ligipääsutasemega treeningud.",
    subscribe: "Kinnita makse",
    activeSubscriptions: "Aktiivsed tellimused",
    noSubscriptions: "Tellimusi veel ei ole.",
    adminTitle: "Stuudio admin",
    adminText: "Halda kategooriaid, treenereid, pakette, videoid ja liikmeid ühest rahulikust juhtpaneelist.",
    categoryManager: "Kategooriate haldus",
    trainerManager: "Treenerite haldus",
    packageManager: "Pakettide haldus",
    videoManager: "Videote haldus",
    userManager: "Kasutajate haldus",
    adminWorkspaceHint: "Vali andmetüüp ja halda seda ühest keskendunud admin-paneelist.",
    adminSearchPlaceholder: "Otsi aktiivsest admin-sektsioonist",
    adminResetPanel: "Lähtesta paneel",
    adminNoMatches: "Praeguse otsinguga sobivaid kirjeid ei leitud.",
    adminSelfDeleteBlocked: "Kasuta väljalogimise nuppu, mitte ära kustuta aktiivset admin-kontot.",
    save: "Salvesta",
    edit: "Muuda",
    delete: "Kustuta",
    cancel: "Tühista",
    duration: "Kestus",
    equipment: "Varustus",
    language: "Keel",
    description: "Kirjeldus",
    videoUrl: "Video URL",
    startDate: "Alguskuupäev",
    price: "Hind",
    durationMonths: "Kuude arv",
    planName: "Paketi nimi",
    trainerBio: "Tutvustus",
    role: "Roll",
    accountStatus: "Konto staatus",
    registerDate: "Registreeritud",
    currentUser: "Praegune kasutaja",
    roleAdmin: "Admin",
    roleTrainer: "Treener",
    roleUser: "Kasutaja",
    statusActive: "Aktiivne",
    statusSuspended: "Blokeeritud",
    assignPlan: "Lisa tellimus",
    currentPlan: "Praegune pakett",
    dashboardGuestCta: "Logi sisse, et avada oma videoteek, pleilistid ja tasuline ligipääs FitNestis.",
    adminOnly: "Admin tööriistad on nähtavad ainult admin-kontole.",
    choosePlaylist: "Aktiivne pleilist",
    choosePlaylistFirst: "Vali esmalt pleilist.",
    createOrChoosePlaylist: "Loo või vali pleilist, et selle videoid hallata.",
    addToPlaylist: "Lisa aktiivsesse pleilisti",
    addedToPlaylist: "Lisatud pleilisti",
    removeFromPlaylist: "Eemalda aktiivsest pleilistist",
    renamePlaylist: "Muuda pleilisti nime",
    videosInPlaylist: "Pleilistis olevad videod",
    emptySelection: "Valitud videosid ei ole",
    statsVideos: "Videod",
    statsTrainers: "Treenerid",
    statsCategories: "Kategooriad",
    statsPackages: "Paketid",
    statsPlaylists: "Pleilistid",
    statsSubscriptions: "Tellimused",
    watchNow: "Ava treening",
    unlockThisVideo: "Ava see treening",
    simulatedCheckoutTitle: "Demomakse",
    simulatedCheckoutText: "Kasuta allolevat demo maksevormi, et avada valitud pakett ja näidata rakenduses ligipääsu muutust.",
    paymentEmail: "Makse e-post",
    paymentCardholder: "Kaardi omanik",
    paymentCardNumber: "Kaardi number",
    selectPlan: "Vali pakett",
    selectedPlan: "Valitud pakett",
    packageIncludes: "Sisaldab",
    accessLabel: "Praegune ligipääs",
    accessNone: "Aktiivne pakett puudub",
    accessStarter: "Starter ligipääs",
    accessPlus: "Plus ligipääs",
    accessFull: "Täisligipääs",
    availableNow: "Praegu saadaval",
    accessNeeded: "Vajab",
    openMembership: "Vaata pakette",
    closeVideo: "Sulge video",
    noCategory: "Kategooria puudub",
    noTrainer: "Treener puudub",
    noLanguage: "Keel puudub",
    noEquipment: "Varustus puudub",
    profileFocus: "Kasutaja fookus",
    trainerDashboard: "Treeneri vaade",
    trainerDashboardText: "Vaata oma treeninguid ja videod, mis on seotud sinu treeneriprofiiliga.",
    nextBestPlan: "Soovitatud järgmine samm",
    paymentSuccess: "Demomakse tehtud ja ligipääs uuendatud.",
    paymentHint: "See maksevorm on turvaline demo, mida kasutatakse pakettide ligipääsu näitamiseks FitNestis.",
    paymentIncomplete: "Täida enne demomakse vorm.",
    lockedCount: "lukus",
    sessionDetailsSoon: "Treeningu kirjeldus lisandub peagi.",
    loadingApp: "FitNest avaneb…",
    signedOut: "Oled välja logitud.",
    refreshSuccess: "Sinu FitNesti sisu on värskendatud.",
    loginSuccess: "Tere tagasi FitNesti.",
    registerSuccess: "Sinu FitNesti konto on valmis.",
  },
};

export type CopySet = (typeof copy)[Language];
